management:
  endpoints.web:
    base-path: /
    path-mapping:
      prometheus: metrics
      metrics: types
    exposure.include: health, info, prometheus, metrics
  metrics.enable:
    jvm: false
    http: false
    spring.kafka: false

monitor-config:
  enable: true
  intervalInMiliseconds: 1000
  histogram: true
  percentiles: 0.99
  expiryMinutes: 1
  bufferLength: 3
  slaInNanos: 1, 2, 5, 10, 20, 30, 40, 50, 75, 100, 150, 200, 250, 500, 1000, 1500, 2000, 5000, 10000
  stopTracking: false

spring:
  kafka:
    bootstrap-servers: "10.60.45.50:9095,10.60.45.51:9095,10.60.45.52:9095"
    acks: all
    retries: 3
    request-timeout: 60000
    retry-backoff: 1000
  datasource:
    url: jdbc:mysql://10.40.81.53:3306/test
    #url: jdbc:mysql://10.50.1.53:3306/test
    platform: mysql
    username: loadtest
    #username: dbgtest
    password: abc@123
    driverClassName: com.mysql.cj.jdbc.Driver

kafka:
  demo:
    topic: JavaSnippet
    group-id: binhcn
    concurrency: 4


