zalopay:
  starter:
    remote-config:
      host: 10.60.45.6
      port: 8500
#      config:
      name: cashier-v16
      enabled: true
      token: 1bfe383f-056e-44c2-7221-30928133e2c2
      prefix: payment-engine/cashier
      data-key: stable
      format: YAML
      profile-separator: '/'
      load-by-version: false
